FROM debian:12-slim

WORKDIR /srv

# install build tools and clone and compile llama.cpp
RUN apt-get update && apt-get install -y build-essential git

RUN git clone https://github.com/ggerganov/llama.cpp.git \
  && cd llama.cpp \
  && make -j

FROM debian:12-slim AS env-deploy

# copy llama.cpp binaries
COPY --from=0 /srv/llama.cpp/main /usr/local/bin/llama
COPY --from=0 /srv/llama.cpp/server /usr/local/bin/llama-server

# copy entrypoint script
COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh

# create llama user and set home directory
RUN useradd --system --create-home llama

USER llama

WORKDIR /home/llama

EXPOSE 8080

ENTRYPOINT [ "/usr/local/bin/docker-entrypoint.sh" ]
